# -*- coding: utf-8 -*-
"""store_sales_ensemble_0.44488.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Gwn_BmxM1_KILboQefyuBmPBroHLCRpt
"""

import pandas as pd
import numpy as np

lgb_pred=np.load('y_pred_lgbm_0.46706.npy')
xgb_pred=pd.read_csv('submission_XGB-0.44_eta_0.1_v3.csv')
ANN_pred=pd.read_csv('submission_keras_0.55428.csv')

#np.reshape(ANN_pred, (-1,1))

#sales_lgb_pred=lgb_pred['sales']
sales_xgb_pred=xgb_pred['sales']
sales_ANN_pred=ANN_pred['sales']

ensemble_sales_pred=0.6*sales_xgb_pred+0.25*lgb_pred+0.15*sales_ANN_pred

submission=pd.read_csv('sample_submission.csv')
submission.head()

submission['sales']=ensemble_sales_pred

submission.head()

submission.to_csv('submission.csv', index=False, float_format='%.3f')